site_name: Code Cube documentation library 
theme:
  name: material 
  logo: code cube logo white.png
  favicon: logo.png
  features:
    - navigation.top
    - navigation.path
    - navigation.sections
  custom_dir: custom_dir
extra_css : [extra.css]

plugins:
  - search

nav:
  #- Sitespeed Monitor: site-speed-monitoring/site_speed.md
  #- DataLayer Guard: datalayer-guard/datalayer_guard.md
  - Configuration Tag Monitor:
      - ⚒️ How to configure?:
          - Client-side: tag-monitor/error-monitoring-client-side.md
          - Server-side: tag-monitor/error-monitoring-server-side.md
      - 💡 Tips & Tricks:
          - Bulk editing your tags in GTM: tag-monitor/tag-bulk0edit.md
          - Enabling Tag Inactivity: tag-monitor/tag-inactivity.md
  - Configuration DataLayer Guard:
    - ⚒️ How to configure?:
        - Monitoring events via Tag Management: datalayer-guard/events-tag-manager.md
 # - Alerting & Notifications

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_fonts:
  - name: Mulish
    files:
      - Mulish-Regular.ttf
      - Mulish-SemiBold.ttf
      - Mulish-Bold.ttf
      - Mulish-Italic.ttf
