site_name: Documentation
theme:
  name: material 
  logo: code cube logo white.png
  favicon: logo.png
  features:
    - navigation.top
    - navigation.path
    - navigation.sections
  custom_dir: custom_dir
extra_css : [extra.css]

plugins:
  - search
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - sections:
    - Overview:
      - Introduction: docs/overview/introduction.md
      - Getting Started: docs/overview/getting-started.md
    - Product implementations:
      - Tag Monitor implementation:
        - Page 1: /tag-monitor/error-monitoring-client-side.md.md
        - Page 2: docs/tag-monitor/error-monitoring-client-side.md
