site_name: Documentation
theme:
  name: material 
  logo: code cube logo white.png
  favicon: logo.png
  features:
    - navigation.top
    - navigation.path
    - navigation.sections
  custom_dir: custom_dir
extra_css : [extra.css]

plugins:
  - search
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Tag Monitor:
    - Product configuration:
      - Page 1: /error-monitoring-client-side.md
