site_name: Code Cube Docs
theme:
  name: material 
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.top
extra_css : [extra.css]

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

